### get all users
GET http://localhost:3001/api/users

### create a user
POST http://localhost:3001/api/users
Content-Type: application/json

{  
  "name": "bugs",
  "username": "bugs@fun.de"
}

### create a user with password
# const user1 = await createUser('test1@example.com', 'Test User 1', 'password123')
# const token1 = await login('test1@example.com', 'password123')
POST http://localhost:3001/api/users
Content-Type: application/json

{  
  "name": "Test User 1",
  "username": "test1@example.com", 
  "password": "password123"
}

### Check Login
POST http://localhost:3001/api/login
Content-Type: application/json

{  
  "username": "test2@example.com",
  "password": "password123"
}

### change username
PUT http://localhost:3001/api/users/bugs1
Content-Type: application/json

{  
  # "name": "Bugs Bad Bunny"
}

### get user
GET http://localhost:3001/api/users/2

