### Get all blogs
GET http://localhost:3001/api/blogs

### Get blogs with react
GET http://localhost:3001/api/blogs?search=react

### Create a blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1Z3NAZnVuLmRlIiwiaWQiOjIsImlhdCI6MTc3Njc3NzA0MX0.A5kwCP2j3tdnWZZUifQt9_kDbwCLoloUhpGrH3XWx1U 

{  
  "author": "Mr Precht",
  "url": "www.bild.de",
  "title": "React", 
  "likes": 4
}

### Modify the likes of a blog
PUT http://localhost:3001/api/blogs/66
Content-Type: application/json

{  
  "likes": 3
}

### Delete a blog
### bugs1 Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1Z3NAZnVuLmRlIiwiaWQiOjIsImlhdCI6MTc3Njc3NzA0MX0.A5kwCP2j3tdnWZZUifQt9_kDbwCLoloUhpGrH3XWx1U
### duffy Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1ZmZ5QGZ1bi5kZSIsImlkIjoxLCJpYXQiOjE3NzY3NzcwMjB9.NtgjaPuPIO3e4IKBf8E0SCxDp5PV73vX6JVuwUKpc5s 
DELETE http://localhost:3001/api/blogs/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1Z3MxIiwiaWQiOjIsImlhdCI6MTc3Njc3MzUzMn0.am2tDsF7UZAqg2xhCE24JzL0Bg2XJJA-Il-et4RJKxM
