### get all users
GET http://localhost:3001/api/users

### create a user
POST http://localhost:3001/api/users
Content-Type: application/json

{  
  "name": "bugs",
  "username": "bugs@fun.de"
}

### change username
PUT http://localhost:3001/api/users/bugs1
Content-Type: application/json

{  
  # "name": "Bugs Bad Bunny"
}

