### get all users
GET http://localhost:3001/api/users

### get user by io
GET http://localhost:3001/api/users/1

### create a user
POST http://localhost:3001/api/users
Content-Type: application/json

{  
  "username": "bugs69",
  "name": "Bugs Bad Bunny"
}

