### get All
GET http://localhost:3001/api/notes

### get non important
GET http://localhost:3001/api/notes?important=false

### get important
GET http://localhost:3001/api/notes?important=true

### get serach 'fresh'
GET http://localhost:3001/api/notes?search=fresh&important=true